#!/usr/bin/perl -w

$file=shift;

while ($attr=shift) {
    if ($attr=~/^(.+)=(.+)$/) {
        system qq(setfattr -n user.$1 -v $2 $file);
    } elsif ($attr=~/^(.+)=$/) {
        system qq(setfattr -x user.$1 $file);
    } else {
        system qq(setfattr -n user.$attr $file);
    }
}
