#!/bin/bash

if [[ "$1" == "1" ]]; then
    sensors | grep Sys\ Temp | cut -c10-16 | sed -re 's/^ +\+//;'
elif [[ "$1" == "2" ]]; then
    sensors | grep CPU\ Temp | cut -c10-16 | sed -re 's/^ +\+//;'
elif [[ "$1" == "3" ]]; then
    sensors | grep AUX\ Temp | cut -c10-16 | sed -re 's/^ +\+//;'
else
    sensors | grep Temp | cut -c1-18 | sed -e 's/ C/°C/'
fi
